name: "Johannes Schickling"
description: "A blog about (web) technology"
author: "Johannes Schickling"

paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'CNAME'] # files to exclude
permalink: /:title
# pygments: true
markdown: redcarpet
production_url: http://schickling.me